# Generated by Django 5.2.7 on 2026-05-27 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav', '0001_initial'),
        ('products', '0004_alter_product_id'),
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='products.product'),
        ),
        migrations.AlterField(
            model_name='fav',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='user.user'),
        ),
    ]
