# Generated by Django 6.0.5 on 2026-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
